---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unleashdemoapp-deployment
  labels:
    app: unleashdemoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unleashdemoapp
  template:
    metadata:
      labels:
        app: unleashdemoapp
    spec:
      containers:
      - name: unleashdemoapp
        image: adamgardnerdt/unleashdemoapp:v1
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: unleashdemoapp
spec:
  type: LoadBalancer
  selector:
    app: unleashdemoapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000